version: "3.8"

services:
  phoenix:
    build: .
    command: sleep infinity
    volumes:
      - ../:/workdir/
      - /var/run/docker.sock:/var/run/docker.sock  # <-- ADD THIS LINE
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
