services:
  phoenix:
    build: 
      context: .
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
    volumes:
      - ../:/workspace/my_app
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
